FROM python:3.9-slim

WORKDIR /app

COPY requirement.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

# main: Look for a file named main.py. app: look for the variable named app = FastAPI()
CMD ["gunicorn", "-w", "4", "-k" "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:8000"]