name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # GitHub pre-installs Docker on all their Ubuntu runners
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Go to my GitHub repository, grab all my files, and copy them onto this runner
    - name: Checkout Repository
      uses: actions/checkout@v6
        
    - name: Test Build - Flask App
      run: docker build -t test-flask-app ./app

    - name: Test Build - Nginx Proxy
      run: docker build -t test-nginx ./nginx

    - name: Calculate short SHA
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: log in to docker hub
      uses: docker/login-action@v4
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push flask app
      uses: docker/build-push-action@v5
      with:
        context: ./app
        # Only push if this is NOT a pull request, To test this during PR first
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-lab-v2-app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/devops-lab-v2-app:${{ steps.vars.outputs.sha_short }}

    
