name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # GitHub pre-installs Docker on all their Ubuntu runners
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Go to my GitHub repository, grab all my files, and copy them onto this runner
    - name: Checkout Repository
      uses: actions/checkout@v6

    - name: Test Build - Flask App
      run: docker build -t test-flask-app ./app

    - name: Test Build - Nginx Proxy
      run: docker build -t test-nginx ./nginx
