name: flask-lab APP

on:
  push:
    branches: ["feature/tech-stack", "main"]
  
jobs:
  build-and-test:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Typo Check
        run: python -m compile_py lab-flask/app.py

      - name: Build Docker Image
        run: docker build -t flask-dev:test ./lab-flask

      - name: Run Docker Container and Test
        run: docker run -d -p 8080:5000 --name test-container flask-dev:test

      - name: 


